search/urls.py
from django.conf.urls import url
from search import views

urlpatterns = [
    # ToDoリスト
    # url(r'^ToDoList/$', views.ToDoList_list, name='todolist_list'),   # 一覧
    # url(r'^Paper/(?P<paper_id>\d+)/$', views.ToDoList_edit, name='paper'),  # 修正

    # 検索
    url(r'^index/$', views.Index, name='do_search'),
    # 内容
    url(r'^content/(?P<paper_id>\d+)/$', views.Content, name='content'),
]

search_engine/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls', namespace='search')),
]

search/models.py
from django.db import models
from django import forms

class Paper(models.Model):
    """論文"""
    title = models.CharField('Title', max_length=200)
    abst = models.TextField('Abstract')

    def __tuple__(self):
        return self.title, self.abst

search/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.http import JsonResponse

from search.models import Paper

import nltk
from nltk.corpus import stopwords
import numpy as np
import math
import re
from sklearn.cluster import KMeans


def prepro(document):
    """文書前処理"""
    tmp = document.replace('.', '').replace(',', '').replace('\"', '').replace('\'', '').replace('¥n', '') #句読点や改行などを削除
    tmp = re.sub(re.compile("[!-/:-@[-`{-~]"), '', tmp) #半角記号を削除
    tmp = tmp.split(" ") # スペースを区切りにリスト化
    return tmp


def removeStoplist(document):
  """ストップワードを取り除く"""
  stoplist_removed_document = []
  for word in document:
      if word not in stopwords.words('english'):
        stoplist_removed_document.append(word)
  return stoplist_removed_document


def stemming(document):
    """ステミング処理"""
    stemmer = nltk.PorterStemmer()
    stem = []
    for word in document:
        stem.append(stemmer.stem(word))
    return stem


def make_term(documents):
    """全文書による単語リストを作成"""
    all_term=[]
    for i in documents:
        for j in i:
            if j not in all_term:
                all_term.append(j)
    return(all_term)


def tf(terms, document):
    """任意の文書のTF値の計算"""
    tf_values = [document.count(term) for term in terms]
    return list(map(lambda x: x/sum(tf_values), tf_values))


def idf(terms, documents):
    """任意の文書のIDF値の計算"""
    return list(map(lambda x : x+1, [math.log10(len(documents)/sum([bool(term in document) for document in documents])) for term in terms]))


def tf_idf(terms, documents):
    """文章毎にTF-IDF値を計算"""
    return [[_tf*_idf for _tf, _idf in zip(tf(terms, document), idf(terms, documents))] for document in documents]


def center(doc_vector, k, pred):
    """クラスタの重心ベクトル算出"""
    center_vec = np.zeros((k,len(doc_vector[0]))) # 重心ベクトルの初期値(クラスタの数*ベクトルの次元数)
    for i in range(k):
        counter = 0
        for j in range(len(doc_vector)):
            if i == pred[j]:
                center_vec[i] += doc_vector[j]
                counter += 1
        center_vec[i] = center_vec[i] / counter
    return center_vec


def clst(doc_vector):
    """文章ベクトルのクラスタリング処理"""
    k = 3
    pred = KMeans(n_clusters=k,random_state=56).fit_predict(doc_vector)
    center_vec = center(doc_vector,k,pred)
    return pred, center_vec


def cos_sim(x,y):
    """コサイン類似度の計算"""
    if np.linalg.norm(x)==0 or np.linalg.norm(y)==0:
        return 0
    else:
        return np.dot(x,y) / (np.linalg.norm(x) * np.linalg.norm(y))


# 行に文書,列に単語のリストを作成
doc = []
# for i in range(20): # file_number
for i in Paper.objects.all():
    tmp = stemming(removeStoplist(prepro(i.abst)))
    doc.append(tmp)

#全出現単語
all_terms = make_term(doc)

# tf-idfを計算し文書ベクトルへ(行に各文書ベクトル、列はベクトルの各次元の要素)
doc_vec = tf_idf(all_terms,doc)

#文書ベクトルをクラスタリングし、クラスタの重心ベクトルを算出
clst_pred, center_vector = clst(doc_vec)
print(clst_pred)


def Index(request):
    """検索結果"""

    result_title = []
    result_abst = []
    len_abst = []
    p_id = []
    search_flag = '0'

    if request.method == 'GET':

        query = request.GET.get('query') #検索ワード：query

        if query:
            query_tmp = stemming(removeStoplist(prepro(query)))

            # クエリのベクトル生成
            query_vec = np.zeros(len(all_terms))
            for i in query_tmp:
                if i in all_terms:
                    query_vec[all_terms.index(i)] = 1

            #クエリベクトルがどのクラスタの重心ベクトルと類似しているかを計算
            near_clst_sim = 0
            for i in range(len(center_vector)):
                clst_sim = cos_sim(query_vec,center_vector[i])
                if near_clst_sim <= clst_sim :
                    near_clst_sim = clst_sim
                    clst_number = i

            # クエリベクトルと類似クラスタ内の各文書ベクトルとのコサイン類似度を算出し、
            # 文書ベクトルと対応するリストの位置に類似度の値を代入
            sim_array = np.zeros(len(doc_vec))
            for i in range(len(doc_vec)):
                if clst_number == clst_pred[i]:
                    sim_array[i] = cos_sim(query_vec,doc_vec[i])

            # 検索ワードとの類似度が高い順にソート(ランキング化)し、その元のindexをリスト化
            dec_doc=[]
            for i in range(len(sim_array)):
                if np.sort(sim_array)[::-1][i] != 0:
                    dec_doc += [np.argsort(sim_array)[::-1][i]]

            # ランキングが高い順にリストに追加
            for i in dec_doc:
                 for j in Paper.objects.all():
                     if (i+1) == j.id:
                         result_title += [j.title]
                         result_abst += [j.abst[:200]]
                         len_abst += [len(j.abst)]
                         p_id += [str(j.id)]

            search_flag = '1'

    d = {
        'query':query,
        'search_flag':search_flag,
        'result_title':result_title,
        'result_abst':result_abst,
        'len_abst':len_abst,
        'p_id':p_id,
        'result_num':str(len(result_abst)),
    }
    return render(request, 'search/index.html',d)


def Content(request,paper_id):

    cont = get_object_or_404(Paper, pk=paper_id)
    contexts = {
        'title':cont.title,
        'abst':cont.abst,
    }
    return render(request,'search/content.html',contexts)

search/templates/base.html
<!-- {% load staticfiles %} -->
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" style="height:100%">
  <head>
  <meta charset="UTF-8">
  <title>{% block title %}Paper Search{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <style>
  body {
    height: 100%;
    background: url("{% static 'image/search.png' %}") center center / contain no-repeat fixed;
  }
  .bkRGBA{
    height: 100%;
    background: rgba(255,255,255,0.9);
  }
  </style>
  {% block extrahead %}{% endblock %}
</head>
{% block body %}
<body>
<div class="bkRGBA">
{% endblock %}
  <h1 style= background-color:#5AF padding: 10px>
    <a href="{% url 'search:do_search' %}" style= "color:#222; padding-left: 50px;">Paper Search</a>
  </h1>

  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</div>
</body>

{% block scripts %}
{% endblock %}

</html>

search/templates/search/content.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Paperの内容{% endblock title %}

{% block extrahead %}
{% load bootstrap %}
<style>
.bk{
  background: url("{% static 'image/document_syorui_pen.png' %}") center center / contain no-repeat fixed;
}
.bkRGBA{
  height: 100%;
  background: rgba(255,255,255,0.9);
}
</style>
{% endblock %}
{% block body %}
  <body class="bk">
    <div class="bkRGBA">
{% endblock %}
{% block content %}
    <br>
    <h2>{{ title }}</h2>
    <font size=4>{{ abst }}</font>
{% endblock content %}

search/templates/search/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Paper Search{% endblock title %}

{% block extrahead %}
{% load bootstrap %}
{% endblock %}

{% block content %}
      <form id="getform" action="" method="get">
        <input id="query" type="text" size="60" name="query" placeholder="検索ワードを入力">
        <input type="submit" class="btn btn-primary" value="検索">
      </form>

      {% if search_flag == '1' and result_num == '0' %}
        検索ワード"<b>{{ query }}</b>" が
        <font color="red">対象のPaperは見つかりません</font><br>
      {% elif search_flag == '1' %}
        検索ワード"<b>{{ query }}</b>" の
        <font color="red">検索結果が {{ result_num }} 件見つかりました</font><br><br>
      {% endif %}

      {% load mytag %}
      {% for paper_id in p_id %}
        <div style="padding: 20px; margin-bottom: 10px; border: 1px solid #333333; background: rgba(255,255,255,0.6);">
          <b><a href="{% url 'search:content' paper_id=paper_id %}">{{ result_title|show_list:forloop.counter0 }}</a></b><br>
          {% if len_abst|show_list:forloop.counter0 <= 200 %}
            {{ result_abst|show_list:forloop.counter0 }}
          {% else %}
            {{ result_abst|show_list:forloop.counter0 }}...
          {% endif %}
        </div>
      {% endfor %}

    </div>
  </div>
{% endblock content %}